package com.example.instafameproj

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import com.google.firebase.storage.StorageReference

// Firebase insists we have a no argument constructor
data class videoData(
    // Auth information
    var uuid : String = "",
    var ref: StorageReference,
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
