package com.example.instafameproj

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId

// Firebase insists we have a no argument constructor
data class VideoMeta(
    // Auth information
    var videoId : String = "",
    var title : String = "",
    var url : String = "",
    var upload_uuid : String = "",
    val timeStamp: Timestamp = Timestamp.now(),
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
